apiVersion: apps/v1
kind: Deployment 
metadata:
  name: flask-deployment-app
spec:
  replicas: 2
  selector: 
    matchLabels:
      app: flask
  template:
    metadata:
      labels: 
        app: flask
    spec:
      containers:
        - name: flask-con
          image: prikale/market-flaskapp:latest
          ports:
            - containerPort: 5000
          